[[experiments]]
id = "case_b"
n_progressions = 100

# ------------------------------------------------------------------- Global Models -- //

[[models]]
id = "optimizer_00"
label = "GD"
description = "Gradient Descent"
params_labels = ["learning_rate", "epsilon"]
params_values = [0.1, 0.001]

# ------------------------------------------------------------------- Global Models -- //

[[models]]
id = "mod_ai_00"
label = "GBM"
description = "Geometric Brownian Motion"
params_labels = ["mu", "sigma"]
params_values = [0.01, 0.001]

[[models]]
id = "mod_eu_00"
label = "GBM"
description = "Geometric Brownian Motion"
params_labels = ["mu", "sigma"]
params_values = [0.01, 0.001]

[[models]]
id = "mod_am_00"
label = "GBM"
description = "Geometric Brownian Motion"
params_labels = ["mu", "sigma"]
params_values = [0.01, 0.001]

# --------------------------------------------------------------- Global Orderbooks -- //

[[exchanges]]
id = "ai_00"
region = "asia"
name = "binance"
category = "cex"

[exchanges.orderbook]
update_freq = 50
bid_price = 100_000.00
bid_levels = [5, 10]
bid_orders = [5, 10]
ticksize = [0.1, 1.0]
ask_price = 100_001.00
ask_levels = [5, 10]
ask_orders = [5, 10]
rands = [-0.01, 0.01]

[[exchanges]]
id = "eu_00"
region = "europe"
name = "kraken"
category = "cex"

[exchanges.orderbook]
update_freq = 50
bid_price = 100_000.00
bid_levels = [5, 10]
bid_orders = [5, 10]
ticksize = [0.1, 1.0]
ask_price = 100_001.00
ask_levels = [5, 10]
ask_orders = [5, 10]
rands = [-0.01, 0.01]

[[exchanges]]
id = "am_00"
region = "americas"
name = "bitso"
category = "cex"

[exchanges.orderbook]
update_freq = 50
bid_price = 100_000.00
bid_levels = [5, 10]
bid_orders = [5, 10]
ticksize = [0.1, 1.0]
ask_price = 100_001.00
ask_levels = [5, 10]
ask_orders = [5, 10]
rands = [-0.01, 0.01]

