[[training]]
epochs = 100
agents = 3
connections = 6

# --- row 0 --- #
[[training.agent_connections]]
from = 0
to = 0
weight = 0.0

[[training.agent_connections]]
from = 0
to = 1
weight = 0.5

[[training.agent_connections]]
from = 0
to = 2
weight = 0.5

# --- row 1 --- #

[[training.agent_connections]]
from = 1
to = 0
weight = 0.5

[[training.agent_connections]]
from = 1
to = 1
weight = 0.0

[[training.agent_connections]]
from = 1
to = 2
weight = 0.5

# --- row 2 --- #

[[training.agent_connections]]
from = 2
to = 0
weight = 0.5

[[training.agent_connections]]
from = 2
to = 1
weight = 0.5

[[training.agent_connections]]
from = 2
to = 2
weight = 0.0

